#!/bin/sh
# tomcat: Start/Stop/Restart tomcat
# chkconfig: 2345 40 20
# description: Tomcat is a Java Servlet Container
# match these values to your environment:
export CATALINA_BASE=/usr/local/tomcat7
export CATALINA_HOME=/usr/local/tomcat7
export CATALINA_TMPDIR=/usr/local/tomcat7/temp
export JRE_HOME=/usr/java/jdk1.7.0_45
# Source function library.
. /etc/init.d/functions TOMCAT=/usr/local/tomcat7
start() {
     echo -n "Starting Tomcat:  "
   su - lyun - c " /usr/local/tomcat7/bin/startup.sh start "
   }
stop() {
    echo -n "Stopping Tomcat: "
        /usr/local/tomcat7/bin/shutdown.sh stop
   }
# See how we were called.
case "$1" in
  start)
      start
  ;;
    stop)
        stop
    ;;
 status)
    ;;
    restart)
       stop
sleep 2
       start
    ;;
 *)
echo "Usage: $0 {start stop restart}" ;;
esac
exit $RETVAL
